### ISSUE TITLE
TesPy code for generating the dataset

### ISSUE THREAD

**Issue by ognjenkundacina** [Keiv4n/IGL#1]
Hello! 

I am trying to implement a similar setup. Can you please share the TesPy code used for generating the dataset.

Kind regards,

Ognjen

**Comment by Keiv4n** [comment]
Hi,

Thanks for your interest. TesPy code for this setup is available at:
https://github.com/EPFL-IMOS/PEGNN_SS/blob/main/Data/DHN_Topology_TESPY.py

Data is also available at:
https://github.com/EPFL-IMOS/PEGNN_SS/tree/main/Data

Best regards,

**Comment by ognjenkundacina** [comment]
Thank you!
